# Generated by Django 5.1.6 on 2025-02-23 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Actif', 'Actif'), ('Passif', 'Passif'), ('Capitaux propres', 'Capitaux propres')], max_length=50)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'Compte',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_acquisition', models.DateField()),
                ('valeur_acquisition', models.DecimalField(decimal_places=2, max_digits=18)),
                ('duree_de_vie', models.IntegerField()),
                ('taux_amortissement', models.DecimalField(decimal_places=4, max_digits=5)),
                ('valeur_residuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Immobilisation',
            },
        ),
        migrations.CreateModel(
            name='PlanComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PlanComptable',
            },
        ),
        migrations.CreateModel(
            name='Tresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flux', models.CharField(choices=[('Entrée', 'Entrée'), ('Sortie', 'Sortie')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tresorerie',
            },
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('justificatif', models.CharField(blank=True, max_length=255, null=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='APPLICATION.compte')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='APPLICATION.compte')),
            ],
            options={
                'db_table': 'Ecriture',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('etat', models.CharField(choices=[('Non paye', 'Non payé'), ('Partiellement paye', 'Partiellement payé'), ('Paye', 'Payé')], max_length=50)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APPLICATION.client')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='APPLICATION.fournisseur')),
            ],
            options={
                'db_table': 'Facture',
            },
        ),
        migrations.AddField(
            model_name='compte',
            name='plan_comptable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APPLICATION.plancomptable'),
        ),
    ]
