# Generated by Django 5.1.6 on 2025-02-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
        migrations.AlterModelTable(
            name='compte',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ecriture',
            table=None,
        ),
        migrations.AlterModelTable(
            name='facture',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fournisseur',
            table=None,
        ),
        migrations.AlterModelTable(
            name='immobilisation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='plancomptable',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tresorerie',
            table=None,
        ),
    ]
