# Generated by Django 5.1.6 on 2025-03-06 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0002_alter_client_table_alter_compte_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='compte',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ecriture',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='immobilisation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plancomptable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tresorerie',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='compte',
            table='compte',
        ),
        migrations.AlterModelTable(
            name='ecriture',
            table='ecriture',
        ),
        migrations.AlterModelTable(
            name='facture',
            table='facture',
        ),
        migrations.AlterModelTable(
            name='fournisseur',
            table='fournisseur',
        ),
        migrations.AlterModelTable(
            name='immobilisation',
            table='immobilisation',
        ),
        migrations.AlterModelTable(
            name='plancomptable',
            table='plancomptable',
        ),
        migrations.AlterModelTable(
            name='tresorerie',
            table='tresorerie',
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='APPLICATION.facture')),
            ],
        ),
    ]
