# Generated by Django 5.1.6 on 2025-03-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPLICATION', '0003_alter_client_options_alter_compte_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='paiement',
            table='paiement',
        ),
    ]
